name: "Build"

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: run install
        uses: pnpm/action-setup@v2.2.2
        with:
          version: 6 # local version is 7 but it's not supported by the action, this is why the next line we use no-frozen-lockfile
      - run: pnpm install --no-frozen-lockfile
      - run: pnpm run build
